# ETL

## Importar librerias

In [1]:
from datetime import datetime
import pandas as pd
from sqlalchemy import create_engine, text
import numpy as np
import pycountry
from rapidfuzz import process, fuzz
import unicodedata

## Extraer datos

In [2]:
# Conexión al origen
ORIGEN_URI = "postgresql://postgres:Nomelase123+@seal-users.c180so2u4aci.us-east-2.rds.amazonaws.com:5432/Users"
engine = create_engine(ORIGEN_URI)

# Extracción e impresión
query = text(
    'SELECT cognito_id, email, username, birthdate, country, state, created_at FROM "usuarios";'
)

with engine.connect() as conn:
    resultado = conn.execute(query)
    df = pd.DataFrame(resultado.fetchall(), columns=resultado.keys())

## Visualizarlos

In [3]:
df.head()

,cognito_id,email,username,birthdate,country,state,created_at
0,615b6530-d0d1-70ea-e8ff-7c1b53a7855c,luiguimelendez5@gmail.com,LuisMData,2006-06-01,México,CDMX,2026-06-14 03:06:19.233045
1,612b7520-30d1-7035-29f1-db46d58bd7a9,luiguimrez5@gmail.com,Luisf,2019-06-13,Panamá,dsf,2026-06-14 05:35:21.636366

#### Eliminar espacios

In [4]:
df['cognito_id'] = df['cognito_id'].str.lower().str.strip()
df['email'] = df['email'].str.lower().str.strip()
df['username'] = df['username'].str.lower().str.strip()
df['birthdate'] = df['birthdate'].str.lower().str.strip()
df['country'] = df['country'].str.lower().str.strip()
df['state'] = df['state'].str.lower().str.strip()

#### Calcular columna edad

In [5]:
df['birthdate'] = pd.to_datetime(df['birthdate'])

# Fecha actual
hoy = pd.Timestamp.now()

# Calcular edad
df['edad'] = (
    hoy.year - df['birthdate'].dt.year
    - (
        (hoy.month < df['birthdate'].dt.month) |
        (
            (hoy.month == df['birthdate'].dt.month) &
            (hoy.day < df['birthdate'].dt.day)
        )
    )
)

#### Calcular rango edad

In [6]:

df['rango_edad'] = pd.cut(
    df['edad'],
    bins=[0, 12, 17, 24, 34, 44, 54, 64, 120],
    labels=[
        'Niño',
        'Adolescente',
        'Joven',
        'Adulto Joven',
        'Adulto',
        'Adulto Maduro',
        'Adulto Mayor',
        'Tercera Edad'
    ],
    include_lowest=True
)

#### Crear columna membresia

In [7]:
df['membresia'] = np.random.choice(
    ['normal', 'premium'],
    size=len(df)
)

#### Correguir pais y estado

In [8]:
import pandas as pd
import pycountry
from rapidfuzz import process, fuzz
import unicodedata


def normalizar(texto):
    texto = str(texto).strip().lower()
    return ''.join(
        c for c in unicodedata.normalize('NFD', texto)
        if unicodedata.category(c) != 'Mn'
    )


paises = [c.name for c in pycountry.countries]

paises_norm = {
    normalizar(p): p for p in paises
}


def corregir_pais(pais):
    pais_norm = normalizar(pais)

    match = process.extractOne(
        pais_norm,
        paises_norm.keys(),
        scorer=fuzz.WRatio
    )

    if match and match[1] >= 80:
        return paises_norm[match[0]]

    return pais


df["country"] = df["country"].apply(corregir_pais)


estados_por_iso = {}

for sub in pycountry.subdivisions:
    iso = sub.country_code  # MX, US, FR, etc.
    estados_por_iso.setdefault(iso, []).append(sub.name)


estados_norm = {
    iso: {normalizar(e): e for e in estados}
    for iso, estados in estados_por_iso.items()
}


def corregir_estado(row):
    pais = row["country"]
    estado = row["state"]

    # convertir país → ISO
    pais_obj = pycountry.countries.get(name=pais)

    if not pais_obj:
        return estado

    iso = pais_obj.alpha_2

    catalogo = estados_norm.get(iso)

    if not catalogo:
        return estado

    estado_norm = normalizar(estado)

    match = process.extractOne(
        estado_norm,
        catalogo.keys(),
        scorer=fuzz.WRatio
    )

    if match and match[1] >= 10:
        return catalogo[match[0]]

    return estado


df["state"] = df.apply(corregir_estado, axis=1)

#### Calcular continente

In [9]:
import pycountry
import pycountry_convert  

continent_map = {
    "AF": "África",
    "AS": "Asia",
    "EU": "Europa",
    "NA": "América del Norte",
    "SA": "América del Sur",
    "OC": "Oceanía",
    "AN": "Antártida",
}


def obtener_continente(pais):
    if pd.isna(pais) or str(pais).strip() == "":
        return "Desconocido"

    try:
        country_matches = pycountry.countries.search_fuzzy(str(pais).strip())

        if not country_matches:
            return "Desconocido"

        country_obj = country_matches[0]

        continent_code = pycountry_convert.country_alpha2_to_continent_code(
            country_obj.alpha_2
        )

        return continent_map.get(continent_code, "Desconocido")

    except Exception as e:
        return "Desconocido"


df["continent"] = df["country"].apply(obtener_continente)

In [10]:
df.head()

,cognito_id,email,username,birthdate,country,state,created_at,edad,rango_edad,membresia,continent
0,615b6530-d0d1-70ea-e8ff-7c1b53a7855c,luiguimelendez5@gmail.com,luismdata,2006-06-01,Mexico,Campeche,2026-06-14 03:06:19.233045,20,Joven,normal,América del Norte
1,612b7520-30d1-7035-29f1-db46d58bd7a9,luiguimrez5@gmail.com,luisf,2019-06-13,Panama,Darién,2026-06-14 05:35:21.636366,7,Niño,premium,América del Norte

#### Cargar datos

In [11]:
DESTINO_URI = "postgresql://postgres:Nomelase123+@seal-users.c180so2u4aci.us-east-2.rds.amazonaws.com:5432/UsersETL"
engine = create_engine(DESTINO_URI)


def cargar_datos_to_rds(df_origen):
    print("[Fase L] Iniciando proceso de carga en AWS RDS...")

    # =========================================================================
    # 2. PREPARACIÓN E INSERCIÓN: TABLA UBICACION
    # =========================================================================
    # Extraemos combinaciones únicas basadas en las columnas de tu dataframe limpio
    df_ubicaciones_nuevas = df_origen[
        ["continent", "country", "state"]
    ].drop_duplicates()

    # Renombramos las columnas para que coincidan exactamente con tu CREATE TABLE
    df_ubicaciones_nuevas = df_ubicaciones_nuevas.rename(
        columns={
            "continent": "continente",
            "country": "pais",
            "state": "estado",
        }
    )

    # Forzamos los tipos VARCHAR (strings limpios)
    df_ubicaciones_nuevas["continente"] = (
        df_ubicaciones_nuevas["continente"].astype(str).str.strip()
    )
    df_ubicaciones_nuevas["pais"] = (
        df_ubicaciones_nuevas["pais"].astype(str).str.strip()
    )
    df_ubicaciones_nuevas["estado"] = (
        df_ubicaciones_nuevas["estado"].astype(str).str.strip()
    )

    print("-> Insertando dimensiones en la tabla 'ubicacion'...")
    # 'if_exists="append"' permite que SERIAL maneje los IDs automáticamente.
    # 'method="multi"' agrupa los inserts en bloques masivos para máxima velocidad.
    df_ubicaciones_nuevas.to_sql(
        name="ubicacion",
        con=engine,
        if_exists="append",
        index=False,
        method="multi",
    )

    # =========================================================================
    # 3. RECUPERACIÓN DE ID_UBICACION GENERADOS POR LA BD
    # =========================================================================
    # Necesitamos traer los IDs autoincrementales que la BD acaba de asignar
    print("-> Sincronizando llaves primarias generadas...")
    df_ubicaciones_db = pd.read_sql(
        'SELECT id_ubicacion, continente, pais, estado FROM "ubicacion";',
        con=engine,
    )

    # =========================================================================
    # 4. PREPARACIÓN E INSERCIÓN: TABLA USUARIO
    # =========================================================================
    # Unimos nuestro dataframe original con el catálogo indexado de la BD
    df_mapeado = df_origen.rename(
        columns={
            "continent": "continente",
            "country": "pais",
            "state": "estado",
        }
    )

    df_usuarios_preparados = pd.merge(
        df_mapeado, df_ubicaciones_db, on=["continente", "pais", "estado"]
    )

    # Construimos la estructura final exigida por tu esquema de destino
    df_usuario_final = pd.DataFrame()
    df_usuario_final["id_usuario"] = (
        df_usuarios_preparados["cognito_id"].astype(str).str.strip()
    )
    df_usuario_final["nombre"] = (
        df_usuarios_preparados["username"].astype(str).str.strip()
    )
    df_usuario_final["edad"] = df_usuarios_preparados["edad"].astype("Int64")
    df_usuario_final["rango_edad"] = (
        df_usuarios_preparados["rango_edad"].astype(str).str.strip()
    )
    df_usuario_final["tipo_membresia"] = (
        df_usuarios_preparados["membresia"].astype(str).str.strip()
    )

    # Si tu tabla destino cuenta con la FK o el campo histórico que sumamos, inclúyelo aquí:
    if "id_ubicacion" in df_usuarios_preparados.columns:
        df_usuario_final["id_ubicacion"] = df_usuarios_preparados[
            "id_ubicacion"
        ].astype(int)

    print("-> Insertando registros en la tabla 'usuario'...")
    df_usuario_final.to_sql(
        name="usuario",
        con=engine,
        if_exists="append",
        index=False,
        method="multi",
    )

    print("[ETL COMPLETO] Carga finalizada exitosamente en AWS RDS.")